server:
  port: 8080
logging:
    config: classpath:logback.xml
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/tutor?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 13579ky
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
         multipart:
              maxFileSize: 100Mb
              maxRequestSize: 100Mb
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuweilai.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql